const fakeData = [
  {
    id: "001",
    name: "Gyros Pork",
    category: "Sandwiches",
    ingredients: [
      "Gyros Pork",
      "French fries",
      "tomato",
      "onions",
      "ketchup",
      "mustard",
    ],
    price: "3.5",
    imageUrl: "gyros.jpg",
  },
  {
    id: "002",
    name: "Gyros Chicken",
    category: "Sandwiches",
    ingredients: [
      "Gyros Chicken",
      "French fries",
      "tomato",
      "onions",
      "ketchup",
      "mustard",
    ],
    price: "3.5",
    imageUrl: "gyros.jpg",
  },
  {
    id: "003",
    name: "Souvlaki Pork",
    category: "Sandwiches",
    ingredients: [
      "Souvlaki Pork",
      "French fries",
      "tomato",
      "onions",
      "ketchup",
      "mustard",
    ],
    price: "4.0",
    imageUrl: "gyros.jpg",
  },
  {
    id: "004",
    name: "Souvlaki Chicken",
    category: "Sandwiches",
    ingredients: [
      "Souvlaki Chicken",
      "French fries",
      "tomato",
      "onions",
      "ketchup",
      "mustard",
    ],
    price: "4.0",
    imageUrl: "gyros.jpg",
  },
  {
    id: "005",
    name: "Schnitzel",
    category: "Sandwiches",
    ingredients: [
      "Schnitzel",
      "French fries",
      "tomato",
      "onions",
      "ketchup",
      "mustard",
    ],
    price: "4.5",
    imageUrl: "gyros.jpg",
  },
  {
    id: "006",
    name: "Souvlaki Chicken Bacon",
    category: "Sandwiches",
    ingredients: [
      "Souvlaki Chicken Bacon",
      "French fries",
      "tomato",
      "onions",
      "ketchup",
      "mustard",
    ],
    price: "4.5",
    imageUrl: "gyros.jpg",
  },
  {
    id: "007",
    name: "Gyros Pork",
    category: "Portions",
    ingredients: ["Gyros Pork", "French fries", "tomato", "onions"],
    price: "7.5",
    imageUrl: "gyros-portion.jpg",
  },
  {
    id: "008",
    name: "Gyros Chicken",
    category: "Portions",
    ingredients: ["Gyros Chicken", "French fries", "tomato", "onions"],
    price: "7.5",
    imageUrl: "gyros-portion.jpg",
  },
  {
    id: "009",
    name: "Souvlaki Pork",
    category: "Portions",
    ingredients: ["Souvlaki Pork", "French fries", "tomato", "onions"],
    price: "8.0",
    imageUrl: "gyros-portion.jpg",
  },
  {
    id: "010",
    name: "Souvlaki Chicken",
    category: "Portions",
    ingredients: ["Souvlaki Chicken", "French fries", "tomato", "onions"],
    price: "8.0",
    imageUrl: "gyros-portion.jpg",
  },
  {
    id: "011",
    name: "Schnitzel",
    category: "Portions",
    ingredients: ["Schnitzel", "French fries", "tomato", "onions"],
    price: "8.5",
    imageUrl: "gyros-portion.jpg",
  },
  {
    id: "012",
    name: "Souvlaki Chicken Bacon",
    category: "Portions",
    ingredients: ["Souvlaki Chicken Bacon", "French fries", "tomato", "onions"],
    price: "8.5",
    imageUrl: "gyros-portion.jpg",
  },
  {
    id: "013",
    name: "Tomato Cucumber",
    category: "Salads",
    ingredients: ["Tomato", "Cucumber", "Onion", "Olive Oil"],
    price: "4.5",
    imageUrl: "salad.jpg",
  },
  {
    id: "014",
    name: "Greek Salad",
    category: "Salads",
    ingredients: [
      "Tomato",
      "Cucumber",
      "Onion",
      "Feta Cheese",
      "Olives",
      "Olive Oil",
    ],
    price: "7.0",
    imageUrl: "salad.jpg",
  },
  {
    id: "015",
    name: "Piatsa",
    category: "Salads",
    ingredients: [
      "Rocket",
      "Tomato",
      "Chicken",
      "Crouton",
      "Manouri Cheese",
      "Honey dressing with lemon",
    ],
    price: "7.0",
    imageUrl: "salad.jpg",
  },
  {
    id: "016",
    name: "Ceasar",
    category: "Salads",
    ingredients: [
      "Lettuce",
      "Chicken",
      "Parmezana Cheese",
      "Ceasar Dressing",
      "Bacon",
      "Tomatini",
    ],
    price: "7.0",
    imageUrl: "salad.jpg",
  },
  {
    id: "018",
    name: "Dakos",
    category: "Salads",
    ingredients: ["Barley rusks", "Mizithra Cheese", "Tomatoes", "Olive Oil"],
    price: "6.0",
    imageUrl: "salad.jpg",
  },
  {
    id: "019",
    name: "Cheese Nuggets",
    category: "Appetizer",
    ingredients: ["Cheese Nuggets", "9 pieces"],
    price: "6.0",
    imageUrl: "feta.jpg",
  },
  {
    id: "020",
    name: "Feta Cheese",
    category: "Appetizer",
    ingredients: ["Feta Cheese", "Olive Oil"],
    price: "4.0",
    imageUrl: "feta.jpg",
  },
  {
    id: "021",
    name: "Kefalotyri Saganaki",
    category: "Appetizer",
    ingredients: [],
    price: "5.0",
    imageUrl: "feta.jpg",
  },
  {
    id: "022",
    name: "Bougiournti",
    category: "Appetizer",
    ingredients: [
      "Feta Cheese",
      "Pepper",
      "Tomato",
      "Gouda Cheese",
      "Olive Oil",
    ],
    price: "5.5",
    imageUrl: "feta.jpg",
  },
  {
    id: "023",
    name: "Xaloumi Cheese",
    category: "Appetizer",
    ingredients: ["Xaloumi Cheese", "5 pieces"],
    price: "5.5",
    imageUrl: "feta.jpg",
  },
  {
    id: "024",
    name: "Hot Pepper",
    category: "Appetizer",
    ingredients: [],
    price: "1.5",
    imageUrl: "feta.jpg",
  },
  {
    id: "025",
    name: "Coca Cola",
    category: "Drinks",
    ingredients: [],
    price: "1.5",
    imageUrl: "coca-cola.jpg",
  },
  {
    id: "026",
    name: "Coca Cola Zero",
    category: "Drinks",
    ingredients: [],
    price: "1.5",
    imageUrl: "coca-cola.jpg",
  },
  {
    id: "027",
    name: "Fanta Orange",
    category: "Drinks",
    ingredients: [],
    price: "1.5",
    imageUrl: "coca-cola.jpg",
  },
  {
    id: "028",
    name: "Fanta Lemon",
    category: "Drinks",
    ingredients: [],
    price: "1.5",
    imageUrl: "coca-cola.jpg",
  },
  {
    id: "029",
    name: "Sprite",
    category: "Drinks",
    ingredients: [],
    price: "1.5",
    imageUrl: "coca-cola.jpg",
  },
  {
    id: "030",
    name: "Juice",
    category: "Drinks",
    ingredients: [],
    price: "1.5",
    imageUrl: "coca-cola.jpg",
  },
  {
    id: "031",
    name: "Water 1.5L",
    category: "Drinks",
    ingredients: [],
    price: "1.5",
    imageUrl: "coca-cola.jpg",
  },
];

export { fakeData };
